name: Private-sync
on:
  schedule:
     - cron: '1 */3 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-Ariszy-Private-JavaScript
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync Ariszy-Private-JavaScript(执意)
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/Ariszy/Private-Script.git"
          source_branch: "master"
          destination_branch: "Ariszy-Private"
          github_token: ${{ secrets.PAT }}
